//DISHES
export const ADD_COMMENTS = 'ADD_COMMENTS'
export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILED = 'DISHES_FAILED';
export const ADD_DISHES = 'ADD_DISHES';

//COMMENTS
export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';

//LEADER
export const LEADER_LOADING = 'LEADER_LOADING';
export const ADD_LEADER = 'ADD_LEADER';
export const LEADER_FAILED = 'LEADER_FAILED';


//FEEDBACK
export const ADD_FEEDBACK = 'ADD_FEEDBACK'
